### ISSUE TITLE
Checkpoints Unavaiable

### ISSUE THREAD

**Issue by ChristophReich1996** [mlzxy/flowdino#1]
Hi @mlzxy, unfortunately, both the both the Google Drive and the provided URL do not work. Is there any other way to share the checkpoints? Thanks for your help!

**Comment by mlzxy** [comment]
Could you try this link:
https://rutgers.box.com/s/86tyrwoeddztbaz381crlwl52qj4zjkf

I just refresh the sharing setting.

Best,
Xinyu

**Comment by ChristophReich1996** [comment]
Thanks, this works! Cheers, Christoph
